config/routes.rb
Rails.application.routes.draw do

  resources :urls
  root 'urls#new'
  get ':shortened_url' => 'urls#show'

end

app/models/url.rb
class Url < ActiveRecord::Base
	validates :original_url, presence: true, uniqueness: { 
    message: "already has been used" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  def new
  	#new will render form for new Url and it is the root page.
  	@url = Url.new
    #Page for top 100 visited page
    @urls = Url.order(visit_count: :desc).limit(100).paginate(:page => params[:page], :per_page => 10)
  end

  def create
  	#It will generate a random text and initialize the visit count
  	require 'securerandom'
    @urls = Url.order(visit_count: :desc).limit(100).paginate(:page => params[:page], :per_page => 10)
    @url = Url.new(url_params)
    @url.shortened_url = SecureRandom.urlsafe_base64(6)
    @url.original_url = @url.original_url.strip
    @url.visit_count = 0
		if @url.save
			flash[:success] = 'URL added and shortened URL is shortenedurlgen.herokuapp.com/'+ @url.shortened_url
      # If you want to run locally replace shortenedurlgen.herokuapp.com with localhost:3000
			redirect_to root_path
		else
			render 'new'
		end
  end

  def index
  	#Page for top 100 visited page
  	@urls = Url.order(visit_count: :desc).limit(100).paginate(:page => params[:page], :per_page => 10)
  	
  end


  def show
  	#get the original url from shortened_url and redirect and increase the visit count
    if params[:shortened_url]
      @url = Url.find_by(shortened_url: params[:shortened_url])
      safeurl = URI.encode(@url.original_url)
      if @url.original_url.start_with?("http://", "https://")
        redirect_to safeurl
        @url.visit_count += 1
        @url.save
      else redirect_to "http://"+safeurl
        @url.visit_count += 1
        @url.save
      end
    else
      @url = Url.find(params[:id])
    end
  end

  protected

		def url_params
			params.require(:url).permit(:original_url)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UrlShortener</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
	<% flash.each do |key, value| %>
		<div class = "alert alert-<%= key %> fade in", id = 'flash'>
			<button class="close" data-dismiss="alert">×</button>
		 	<%= value %> 
		</div>
	<% end %>
</div>
<%= yield %>

</body>
</html>

app/views/urls/index.html.erb
<h3>Top 100 Visited Sites</h3>
<div class="container">
	<table class="table table-hover">
	  <tr>
	    <th>Original URL</th>
	    <th>Shortened URL</th>
	    <th>Visit Count</th>
	  </tr>
	 
	  <% @urls.each do |row| %>
	    <tr>
	      <td><%= row.original_url %></td>
	      <td>shortenedurlgen.herokuapp.com/<%= row.shortened_url %></td>
	      <td><%= row.visit_count %></td>
	  <% end %>
	</table>
</div>

app/views/urls/new.html.erb
<% if @url.errors.any? %>
  <div class='alert alert-danger'> 
    <ul>
    <% @url.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= form_for @url,url: urls_path,html: {method: 'post'}  do |f| %>
	<div class="container">
	  <div class="panel panel-default shadow">
	  	<div class="panel-heading">
	  		<h4>Enter URL to shorten it .</h4>
	  	</div>	
		  <div class="panel-body">
				<div class="form-group col-md-8 col-md-offset-2">
					<%= f.label :original_url ,"Enter URL:"%>
					<%= f.text_field :original_url, class: "form-control" , required: true, placeholder: "Enter Original Url"%>
				</div>
				
				<div class='col-md-4 col-md-offset-5'>			
					<%= f.submit 'Submit', class: "btn btn-primary" %>
				</div>
			</div>
		</div>		
	</div>	
<% end %>



<h3><center>Top 100 Visited Sites </center></h3>

<div class="container">

	<table class="table table-hover">
	  <tr>
	    <th>Original URL</th>
	    <th>Shortened URL</th>
	    <th>Visit Count</th>
	  </tr>
	 
	  <% @urls.each do |row| %>
	    <tr>
	      <td><%= row.original_url %></td>
	      <td>shortenedurlgen.herokuapp.com/<%= row.shortened_url %></td>
	      <td><%= row.visit_count %></td>
	    </tr>  
	  <% end %>
	</table>

	<div class="apple_pagination">
    <%= will_paginate @urls, :container => false %>
  </div>
</div>